import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://103.204.95.212:8084/")
    page.get_by_role("textbox", name="Username or email").click()
    page.get_by_role("textbox", name="Username or email").fill("user@gmail.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("12345")
    page.get_by_role("checkbox", name="Remember Me").check()
    page.get_by_role("button", name="LOGIN").click()
    page.get_by_role("button", name="Capacity Insights").click()
    page.get_by_role("button", name="Supply Insights").click()
    page.get_by_role("button", name="Part Allocation Insights").click()
    page.get_by_role("img", name="Scenario Authoring &").click()
    page.locator(".css-hyzecx").first.click()
    page.get_by_role("option", name="PHX4").click()
    page.locator(".css-fplv3z-control > .css-1dyz3mf > .css-hyzecx").first.click()
    page.get_by_role("option", name="Firebond").click()
    page.locator("div:nth-child(3) > .css-b62m3t-container > .css-fplv3z-control > .css-1dyz3mf > .css-hyzecx").click()
    page.get_by_role("option", name="Big Box LV Switchgear").click()
    page.get_by_role("textbox").fill("2025-06-12")
    page.get_by_role("slider").first.fill("0.65")
    page.get_by_role("slider").nth(1).fill("7")
    page.get_by_role("slider").nth(2).fill("16")
    page.get_by_role("button", name="Generate & Visualize Supply").click()
    page.locator("circle").nth(4).click()
    page.locator("circle:nth-child(10)").click()
    page.locator("circle:nth-child(7)").click()
    page.get_by_role("button", name="Edge Metrics").click()
    page.get_by_role("button", name="Configuration and Solve").click()
    page.get_by_role("slider", name="Min: 0 | Max:").first.fill("0.4")
    page.get_by_role("slider", name="Min: 0 | Max:").nth(1).fill("0.3")
    page.get_by_role("slider", name="Min: 0 | Max:").nth(2).fill("0.3")
    page.get_by_role("slider", name="Min: 0 | Max:").nth(3).fill("0.3")
    page.get_by_role("spinbutton").click()
    page.get_by_role("spinbutton").fill("130")
    page.get_by_role("button", name="Run Optimization").click()
    page.locator("circle:nth-child(10)").click()
    page.locator("circle").nth(1).click()
    page.get_by_role("button", name="Granular View").click()
    page.get_by_role("combobox").first.select_option("DC-Chicago")
    page.get_by_role("combobox").nth(1).select_option("Lane-West")
    page.get_by_role("slider").first.fill("0.93")
    page.get_by_role("slider").nth(1).fill("0.2")
    page.get_by_role("slider").nth(2).fill("0.8")
    page.get_by_role("slider").nth(3).fill("0.88")
    page.get_by_role("slider").nth(4).fill("0.55")
    page.get_by_test_id("rf__node-Firebond").click()
    page.get_by_test_id("rf__node-Procurement").click()
    page.get_by_test_id("rf__node-DC-Austin").click()
    page.get_by_test_id("rf__node-DC-Chicago").click()
                                                   
    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
