import re
import time
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://103.204.95.212:8084//")
    page.get_by_role("textbox", name="Username or email").click()
    page.get_by_role("textbox", name="Username or email").fill("user@gmail.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("12345")
    page.get_by_role("checkbox", name="Remember Me").check()
    page.get_by_role("button", name="LOGIN").click()
    page.get_by_role("img", name="Report").click()
    page.get_by_role("button", name="Go").click()

    page.wait_for_timeout(1000)
    page.mouse.wheel(0, 1500)

    # page.locator("path").nth(4).click()
    page.get_by_role("button", name="Identified Trends").click()
    time.sleep(1)
    page.get_by_role("button", name="Emerging Business").click()
    time.sleep(1)
    page.get_by_role("button", name="Strategic Recommendations").click()
    time.sleep(1)
    page.get_by_role("button", name="Turning Points And Timeline").click()
    time.sleep(1)
    page.get_by_role("button", name="Quantitative Forecasts And").click()
    time.sleep(1)
    page.get_by_role("img", name="3, 500. Microsoft Mount").click()
    page.locator("rect").nth(2).click()
    page.get_by_role("img", name="2, 100. Great Lakes Data").click()
    page.get_by_role("img", name="3, 77. Great Lakes Data").click()
    page.get_by_role("img", name="1, 224. Great Lakes Data").click()
    page.get_by_role("button", name="Conclusion").click()
    time.sleep(1)
    page.get_by_role("img").first.click()
    page.get_by_role("img", name="Report").click()
    time.sleep(1)
    page.get_by_role("combobox").select_option("nuclear")
    time.sleep(1)
    page.get_by_role("button", name="Go").click()
    page.wait_for_timeout(1000)
    page.mouse.wheel(0, 1500)
    # page.get_by_role("img").nth(5).click()
    page.get_by_text("Identified Regulatory RisksJanuary 19-25, 2026: China competitive pressure").click()
    page.get_by_role("button", name="Key US Nuclear Policies").click()
    page.get_by_role("button", name="Quantitative Forecasts And").click()
    page.get_by_role("img", name="4, 2,728. DOE Uranium").click()
    page.get_by_role("img", name="2, 900. DOE Uranium").click()
    page.get_by_role("img", name="1, 900. DOE Uranium").click()
    page.get_by_role("button", name="Strategic Opportunities For").click()
    page.get_by_role("button", name="Strategic Recommendations").click()
    page.get_by_role("button", name="Conclusion").click()
    page.locator("#frequency").select_option("monthly")
    # page.get_by_role("img").nth(5).click()
    page.wait_for_timeout(1000)
    page.mouse.wheel(0, 1500)
    page.get_by_role("img", name="3, 2. December 2025 Nuclear-").click()
    time.sleep(1)
    page.get_by_role("button", name="Strategic Opportunities For").click()
    time.sleep(1)
    page.get_by_role("button", name="Strategic Recommendations").click()
    time.sleep(1)
    page.get_by_role("button", name="Conclusion").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
